github/pages-health-check

lib/github-pages-health-check.rb, spec/github_pages_health_check_spec.rb
Many apex domains like http://getbootstrap.com/ use A records (rather than ALIAS/ANAME records):
```
› dig getbootstrap.com
;getbootstrap.com.		IN	A
getbootstrap.com.	9072	IN	A	192.30.252.154
getbootstrap.com.	9072	IN	A	192.30.252.153
```
GitHub Pages will sometimes respond with a `302 Found` for these domains:
```
› curl -I http://getbootstrap.com/
HTTP/1.1 302 Found
Location: /
```
Previously the GitHubPages::HealthCheck#served_by_pages? check could fail because it would make a request which would respond with a `302 Found` and the `Server: GitHub.com` header wouldn't be included in the response.
This fixes the issue by retrying the request, which should then result in a `200 OK` response which includes the `Server: GitHub.com` header.
/cc @benbalter
=> Follow redirects in GitHubPages::HealthCheck#served_by_pages?

.travis.yml, lib/github-pages-health-check.rb, spec/github_pages_health_check_spec.rb
In our prod environment, resolv.conf includes `search github.com`. This leads to pages-health-check returning OK for domains like `this-does-not-exist.io`, because:
```
$ host this-does-not-exist.io
this-does-not-exist.io.github.com is an alias for github.map.fastly.net.
github.map.fastly.net has address 199.27.75.133
```
cc @jdennes @github/pages
=> Handle NXDOMAIN correctly.

github-pages-health-check.gemspec, lib/github-pages-health-check.rb, spec/github_pages_health_check_cloudflare_spec.rb, spec/github_pages_health_check_spec.rb
This adds a `proxied?` method to check if a domain is served by pages, but is proxied by a third-party service. If so, the Health Check shouldn't raise CNAME/A record errors.
The logic is as follows. A domain is proxied if:
1. It's served by a Cloudflare IP (existing logic)
2. The site returns GitHub server headers and it isn't:
1. Pointed at a GitHub Pages IP, or
2. Pointed at a GitHub Pages domain
(I also cleaned up some new test-related warnings that recently appeared by explicitly defining an expected error and explicitly vendoring test dependencies)
/cc @github/pages, @konklone
=> Check if domain is proxied

lib/github-pages-health-check.rb, spec/github_pages_health_check_spec.rb
This passes some sane defaults to typhoeus when performing the `served_by_pages?` check. Specifically:
* Only make a `HEAD` request to save bandwidth
* Accept gzip 
* Set a 10 second timeout
* Pass a custom user agent (Typhoeus is blocked in some cases)
=> Smarter Typhoeus options

github-pages-health-check.gemspec, lib/github-pages-health-check.rb, spec/github_pages_health_check_spec.rb, spec/spec_helper.rb
This stubs out all the net requests related to [the proxy check](https://github.com/github/pages-health-check/pull/21) to make tests faster and more deterministic. With the exception of DNS calls, the test suite should make no net requests to live websites now.
=> Stub net requests when testing

github-pages-health-check.gemspec, lib/github-pages-health-check.rb, spec/github_pages_health_check_spec.rb
Apparently the native URI class isn't fully RFC compliant and doesn't like domains with underscores. See https://stackoverflow.com/questions/5208851/is-there-a-workaround-to-open-urls-containing-underscores-in-ruby.
=> Use addressable::uri to support domains with underscores

lib/github-pages-health-check.rb
Before we were using `response.success?` which returns `false` for non-200 response codes including 30x and 40x status. 
Even if a GitHub Pages site isn't set up (e.g., `/` 404s`), the `served_by_pages?` check should still be able to determine if it's the Pages server, so long as we're able to connect and we don't time out.
Note, when mocking response, `response.return_code` appears to be `nil`.
Cribbed from https://github.com/typhoeus/typhoeus/blob/35a4d5b6f7c818a0c11b0c1e10a20b30c754e169/lib/typhoeus/response/status.rb#L48-L50.
=> Properly detect if domain is served by pages for non-200 response codes

github-pages-health-check.gemspec
This fixes an error where net-dns does not properly query some domains resulting in an `undefined method `first' for false:FalseClass` or `undefined method `value' for example.com. 1800 IN A XXX.XXX.XXX.XXX:Net::DNS::RR::A`
=> Require net-dns ~> 0.8

lib/github-pages-health-check.rb, lib/github-pages-health-check/errors/invalid_dns.rb, lib/github-pages-health-check/version.rb, spec/github_pages_health_check_spec.rb
This creates a shared 10 second timeout between HTTP and DNS checks, and better guards against failing loudly if the DNS check fails for whatever reason.
If the DNS check fails, any check that relies on DNS will return nil, rather than returning a false positive/negative. Check! will return an InvalidDNS error.
Last, memoize served_by_pages? to save on subsequent calls (which may also timeout).
/cc @nuclearsandwich
=> Add timeout to DNS check

lib/github-pages-health-check.rb
Ruby treats `nil` and `false` the same when they're on the left hand side of a `||=`. There are a couple of slow bits of code that are supposed to run once, but could run on each call, if they return `nil` or `false`. This branch changes them to be more explicit about how they handle their instance variables to ensure that the falsy results don't lead to a retry on the next call.
* `#dns` - This can be an array of results or `nil`. Before this branch, `@dns == nil` initially and if the dns results should be `nil`. This branch changes the latter case to set `@dns = false`, and it checks explicitly for `@dns.nil?` to know if it should actually look up any values.
* `#served_by_pages?` - This will return `true` or `false`. Before this branch, `@served_by_pages` would be `nil` on init and a …
=> Memoize falsy values

lib/github-pages-health-check.rb, spec/github_pages_health_check_spec.rb
This will behave correctly even if a domain is not a listed public suffix. This could happen if a domain is a delegated zone, which can't have a CNAME record at the apex.
cc @benbalter @jdennes @spraints
=> Use the existence of an NS record to determine whether a domain is an apex domain

lib/github-pages-health-check.rb, script/cibuild, script/test, spec/github_pages_health_check_spec.rb
When we're trying to run a health check and we copy it from the address bar,
it often automatically has looks like `http://#{domain}/`. This change makes
the constructor more tolerant so this becomes less of a pain point.
/cc @github/pages
=> HealthCheck.new should accept domains and URI's

lib/github-pages-health-check/domain.rb, script/check, spec/github_pages_health_check_domain_spec.rb
This pull request expands the `InvalidCNAME` check to look for two additional conditions:
1. The domain is a CNAME, but the CNAME is to `page.github.com`, not `[username].github.io`
2. The domain is a CNAME, but the CNAME is to `github.map.fastly.net` directly, not to `[username].github.io`
In both cases, the misconfiguration makes it harder for us to prevent abuse at the DNS level.
To accomplish this, `Domain#cname` now returns a Domain object, rather than the CNAME string, allowing us to more easily run checks on the target domain (where the CNAME resolves to).
Fixes https://github.com/github/pages-health-check/issues/40.
=> Check if domain is CNAME to pages.github.com or directly to Fastly

lib/github-pages-health-check/printer.rb
This prevents YAML from outputting ugliness like this:
```yml
reason: !ruby/exception:GitHubPages::HealthCheck::Errors::BuildError
message: The tag `blah` in `index.html` is not a recognized Liquid tag. For more
information, see https://help.github.com/articles/page-build-failed-unknown-tag-error.
```
=> Call to_s on the reason field before converting to a hash

lib/github-pages-health-check.rb
That should be more than enough for most domains, and will speed things up for domains that don't resolve.
=> Reduce DNS timeout to 5 seconds

lib/github-pages-health-check/domain.rb, spec/github_pages_health_check_domain_spec.rb
This pull request places an `unless valid_domain?` escape hatch before any network call to reduce the likelihood that the Gem will waste time trying to resolve a obviously unresolvable domain (e.g., `foo.invalid`).
This will be a *slight* change in behavior and a *slight* change in philosophy. 
Currently, the behavior is to return all the information we can about a given domain, even it's invalid, and only used `valid_domain?` to guard against false positives.
If merged, this pull request will change that behavior, such that the gem will return **minimal** information for invalid domains, but will never raise an error.
The idea here, is some domains are valid, but not represented in public suffix. Rather than raise a false positive for one of these edge case domains, return a potential …
=> Use valid_domain? as an early escape hatch

lib/github-pages-health-check/domain.rb, spec/github_pages_health_check_domain_spec.rb
This prevents the health check from erring out on domains with whitespace and FQDNs with trailing periods.
In doing so, this rename the private `host_from_uri` to `normalize_host`.
=> Better domain normalization

lib/github-pages-health-check/domain.rb, spec/github_pages_health_check_domain_spec.rb
So `normalize_domain` should return `nil`, not an empty string.
This prevents undefined method errors down the line, since `domain_valid?` is already an early escape hatch.
=> Empty hosts are also invalid

lib/github-pages-health-check/domain.rb, lib/github-pages-health-check/error.rb, lib/github-pages-health-check/errors/build_error.rb, lib/github-pages-health-check/errors/deprecated_ip_error.rb, lib/github-pages-health-check/errors/invalid_a_record_error.rb, lib/github-pages-health-check/errors/invalid_cname_error.rb, lib/github-pages-health-check/errors/invalid_dns_error.rb, lib/github-pages-health-check/errors/invalid_domain_error.rb, lib/github-pages-health-check/errors/invalid_repository_error.rb, lib/github-pages-health-check/errors/missing_access_token_error.rb, lib/github-pages-health-check/errors/not_served_by_pages_error.rb, lib/github-pages-health-check/repository.rb, spec/github_pages_health_check_domain_spec.rb, spec/github_pages_health_check_error_spec.rb, spec/github_pages_health_check_errors_spec.rb
This pull request is intended to move the more descriptive human-readable error messages that GitHub Pages uses into the open source Ruby gem, where they can be shared between implementations. Specifically, errors, as exposed via `HealthCheck#reason` have an expanded `#message` method, and also expose `#message_with_url` which would provide a URL to the help docs.
The code's definitely a bit rough and could use some :eyes:.
=> Better human-readable error messages 

lib/github-pages-health-check/error.rb
Right now, reason is outputted as the class's default `to_s`, when called via e.g., `script/check` or `check.to_s`. 
This adds an explicit `to_s` method that includes the message and error class.
=> Fix output of reason when pretty printing

lib/github-pages-health-check/domain.rb
This datacenter will be deprecated on August 21st, 2016.
=> Add old Fastly JFK datacenter to list of legacy IPs

github-pages-health-check.gemspec, lib/github-pages-health-check/domain.rb
This PR upgrades the `public_suffix` gem to v2.0.
We only hit one snafu:
> Now that the library is 100% compliant with the official PublicSuffix algorithm, if a domain passed as input doesn't match any rule, the wildcard rule `*` is assumed. This means that unlisted TLDs will be considered valid by default, when they would have been invalid in 1.x. However, you can override this behavior to emulate the 1.x behavior if needed.
Upgrading documentation is here: https://github.com/weppos/publicsuffix-ruby/blob/v2.0.3/2.0-Upgrade.md
/cc @github/pages for review.
=> Upgrade PublicSuffix to v2

lib/github-pages-health-check/domain.rb, spec/github_pages_health_check_domain_spec.rb
If you do a `dig` and you get:
```text
;; QUESTION SECTION:
;sub.example.com.        IN    A
;; ANSWER SECTION:
sub.example.com.    704    IN    CNAME    \@.
```
...then you should _not_ get a healthy CNAME.
Fixes #60.
/cc @github/pages @antn
=> Domain#cname? should return false if the value of the CNAME is bad

lib/github-pages-health-check/domain.rb, spec/github_pages_health_check_domain_spec.rb
When a domain has MX records, it cannot be a CNAME. Therefore, if my subdomain, e.g. foo.example.com, has MX records, the health checker should ensure it is an A record pointing to the GHP servers.
/cc @github/pages for review.
Fixes #56.
=> Domain#should_be_a_record?: also check for existence of MX records

.travis.yml, lib/github-pages-health-check/cdns/fastly.rb, lib/github-pages-health-check/domain.rb, spec/github_pages_health_check/domain_spec.rb
=> Some updates for Fastly logic

github-pages-health-check.gemspec, lib/github-pages-health-check.rb, lib/github-pages-health-check/caa.rb, lib/github-pages-health-check/domain.rb, spec/github_pages_health_check/caa_spec.rb
Also adds dnsruby since net-dns doesn't support CAA records. (#79)
CAA records are a way for a domain owner to limit which Certificate Authorities are authorized to issue a certificate for the given domain. These can apply at either the subdomain or parent domain level, so we have to check both to get an accurate picture of whether a particular Certificate Authority is permitted.
=> Check CAA records

lib/github-pages-health-check/domain.rb
Requesting ANY is deprecated and no one is actually responding with valid records.
The perils of stubbing responses...
```text
$ dig ANY parkermoore.de
...
;; ANSWER SECTION:
parkermoore.de.		3789	IN	HINFO	"ANY obsoleted" "See draft-ietf-dnsop-refuse-any"
...
```
This patch instead requests A, CNAME, and MX records.
=> Request A, CNAME, and MX records explicitly

lib/github-pages-health-check/domain.rb, spec/github_pages_health_check/domain_spec.rb
Modifies #84 to un-deprecate the 192 IP addresses, but to not allow them for HTTPS eligibility.
=> Don't deprecate the 192.30.252.15{3,4} quite yet

lib/github-pages-health-check/checkable.rb
This allows a `Checkable` to be a member of another item that has a `to_json` method, like `Hash`.
Example:
```ruby
require 'json'
require 'github-pages-health-check'
entry = { check: GitHubPages::HealthCheck::Domain.new("www.parkermoore.de") }
entry.to_json
```
That currently fails with an `ArgumentError`, but this PR makes it work.
=> Custom #to_json methods must accept the state parameter

.rubocop.yml, lib/github-pages-health-check.rb, lib/github-pages-health-check/error.rb, lib/github-pages-health-check/errors/build_error.rb, lib/github-pages-health-check/errors/deprecated_ip_error.rb, lib/github-pages-health-check/errors/invalid_a_record_error.rb, lib/github-pages-health-check/errors/invalid_cname_error.rb, lib/github-pages-health-check/errors/invalid_dns_error.rb, lib/github-pages-health-check/errors/invalid_domain_error.rb, lib/github-pages-health-check/errors/not_served_by_pages_error.rb, lib/github-pages-health-check/printer.rb, lib/github-pages-health-check/repository.rb, lib/github-pages-health-check/site.rb, lib/github-pages-health-check/version.rb
Targeting Ruby 2.4 meant rubocop insisted on using the `&.` operator which is a no-go in Ruby 2.2
Ruby 2.2 is still supported by github-pages: https://github.com/github/pages-gem/pull/554
=> Target Ruby 2.2 & fix syntax errors

lib/github-pages-health-check/caa.rb, lib/github-pages-health-check/domain.rb, spec/github_pages_health_check/domain_spec.rb
We have resources.github.com which has MX records. According to the DNS spec, it then *cannot* have a CNAME record, as we would normally recommend. This PR allows A records for *.github.com, while still disallowing it for *.github.io (not sure why we checked that in the first place?).
It also fixes a problem where we were requesting CAA records with a `nil` domain, so I fixed it to catch nils better. The nil was from `PublicSuffix.domain(host)`.
Fixes https://github.com/github/resources/issues/200
=> Fix should_be_a_record? to response *.github.com domains

lib/github-pages-health-check.rb, lib/github-pages-health-check/caa.rb, lib/github-pages-health-check/domain.rb, lib/github-pages-health-check/resolver.rb, spec/github_pages_health_check/resolver_spec.rb
DNS caching causes all sorts of issues, because checking the domain once caches the record
on many layers between the querying host and the authoritative nameservers.
To get around caching, simply ask the authoritative nameservers for the domain, bypassing
the DNS in the local network and all networks in between.
=> Check authoritative nameservers for a domain

.rubocop.yml, lib/github-pages-health-check/domain.rb, lib/github-pages-health-check/errors/invalid_aaaa_record_error.rb, lib/github-pages-health-check/resolver.rb, spec/github_pages_health_check/domain_spec.rb, spec/github_pages_health_check/errors_spec.rb
GitHub pages only supports ipv4 at this time. Having AAAA records for a
pages domain is wrong and will lead to certificate enrollment failures,
as Let's Encrypt would connect to the wrong host.
=> Add a check for AAAA records

lib/github-pages-health-check/domain.rb
These will now be printed out when you call `#to_hash` or `#to_json` on a Domain object.
It seemed like useful information to include, especially the `#reason`!
=> Add #valid? and #reason to Domain HASH_METHODS

lib/github-pages-health-check.rb, lib/github-pages-health-check/caa.rb, lib/github-pages-health-check/domain.rb, lib/github-pages-health-check/redundant_check.rb, lib/github-pages-health-check/repository.rb, lib/github-pages-health-check/resolver.rb, lib/github-pages-health-check/site.rb, script/cibuild, spec/github_pages_health_check/domain_spec.rb, spec/github_pages_health_check/redundant_check_spec.rb, spec/github_pages_health_check/repository_spec.rb, spec/github_pages_health_check/resolver_spec.rb, spec/github_pages_health_check_spec.rb
Options include 'default', 'authoritative', or an array of nameserver IP's.
Added `GitHubPages::HealthCheck::RedundantCheck.new(domain)` which provides `#valid?`, `#https_eligible?` and `#check`. The last method, `#check`, returns the `Domain` instance which was "most valid".
=> Allow Domain to specify what kind of nameservers it wants to use

lib/github-pages-health-check/domain.rb
Let's Encrypt prefers IPv6 records when issuing a certificate for a domain. We should filter any domains which have AAAA records, since that is not compatible with HTTPS eligibility.
=> https_eligible?: do not allow AAAA records

lib/github-pages-health-check/domain.rb, lib/github-pages-health-check/redundant_check.rb, lib/github-pages-health-check/resolver.rb, spec/github_pages_health_check/site_spec.rb
Querying a resolver like 8.8.8.8 and 1.1.1.1 enforce DNSSEC internally and provide another possibility for valid answers in the redundant check.
=> Add support for querying public resolvers

lib/github-pages-health-check/resolver.rb
[Dnsruby](https://github.com/alexdalitz/dnsruby) by default appears to cache results internally, which prevents the redundant checking functionality as implemented in https://github.com/github/pages-health-check/pull/90 and https://github.com/github/pages-health-check/pull/98 from performing as expected.
In particular, the earlier cached entries from the default nameservers are returned when later trying the authoritative and public nameservers.
This PR disables this caching in Dnsruby.
While rudimentary, I was able to test this was effective by performing the following two queries in `script/console`, spaced sufficiently apart to be able to determine by the returned TTLs that they were not sharing a local cached entry:
```
GitHubPages::HealthCheck::Domain.new("pages.github.com", …
```
=> Disable DNS Result Caching

lib/github-pages-health-check.rb, lib/github-pages-health-check/caa.rb, lib/github-pages-health-check/domain.rb, lib/github-pages-health-check/resolver.rb, spec/github_pages_health_check/domain_spec.rb
I came across a couple of issues with [internationalised domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name) today that I hope to solve in this PR.
---
PublicSuffix doesn't support Punycode encoded internationalised public suffixes, and instead expects them to be Unicode encoded (weppos/publicsuffix-ruby#46). If you feed in a Punycode encoded   public suffix, then no result, or a more broader result, may be returned.
Impacts:
- `Domain.valid_domain?` can return `false`, leading to almost everything in `Domain` failing, including `Domain.https_eligible?` always returning `false`.
- `CAA.records` isn't able to retrieve the CAA records for the apex domain.
---
Unfortunately Dnsruby is the reverse way around, and expects the internationalised domain to be Punycode …
=> Improved support for internationalised domains

lib/github-pages-health-check/caa.rb, spec/github_pages_health_check/caa_spec.rb
Fixes #103 by passing `host.split(".").drop(1).join(".")` through to `get_caa_records` as the fallback instead of `PublicSuffix.domain(unicode_host)`.
This is in line with [RFC 6844](https://tools.ietf.org/html/rfc6844) errata [eid5065](https://www.rfc-editor.org/errata/eid5065), as implemented by Let's Encrypt.
`host.split(".").drop(1).join(".")` will return the parent FQDN immediately above `host`. For example `sub.example.com` for `www.sub.example.com`.
```ruby
get_caa_records("www.sub.example.com") | get_caa_records("example.com")
```
```ruby
get_caa_records("www.sub.example.com") | get_caa_records("sub.example.com")
```
=> Update CAA verification to check immediate parent rather than public suffix domain

github-pages-health-check.gemspec
Bumps the Public Suffix gem, which is now in the 3.x release series as of early last year. This bump will allow GitHub Pages HTTPS support for a number of newer Public Suffixes.
/cc @github/pages
=> Bump public_suffix requirement up to 3.0

lib/github-pages-health-check/caa.rb, lib/github-pages-health-check/domain.rb, lib/github-pages-health-check/repository.rb, spec/github_pages_health_check/domain_spec.rb
The existing logic considers a custom domain that itself is directly considered a Private TLD in the Public Suffix List as not valid, preventing the issuance of a certificate.
Private TLDs in this context are legitimate Internet resolvable domains that have been added to the Public Suffix List by their owners. An example of a Private TLD is `githubusercontent.com`.
The existing logic would deem `subdomain.githubusercontent.com` as valid, but `githubusercontent.com` as not valid.
It is acceptable for Private TLD's to host content directly. Additionally, Let's Encrypt will issue a certificate for a Private TLD. Therefore it is possible for a Private TLD in this context, such as `githubusercontent.com`, to be used as a custom domain with GitHub Pages.
As our Public Suffix usage here is …
=> Support Private Public Suffix TLDs when verifying that a domain is valid

lib/github-pages-health-check/caa.rb, lib/github-pages-health-check/domain.rb, spec/github_pages_health_check/caa_spec.rb, spec/github_pages_health_check/domain_spec.rb
This PR attempts to fix a bug in our CAA checking.
1. Where the domain in question is a CNAME to username.github.io, then only check the CAA records for that one domain. Its parent SHOULD NOT be checked.
2. Where the domain in question uses A records to point to GitHub Pages IPs, then check the CAA records for both it and its parent domain.
Example:
1. `www.example.com` is a CNAME to `example.github.io`. Check only CAA on `www.example.com`.
2. `foobar.example.com` uses A records to point to GitHub Pages IPs. Check CAA for `foobar.example.com` AND `example.com`.
/cc @github/pages
=> For CNAME records, only check CAA records for the domain, not its parent

github-pages-health-check.gemspec, lib/github-pages-health-check/domain.rb
Ruby 2.7 adds some new warnings. In particular, previously if a method was
defined with keyword arguments, you could create a hash and pass it to the
method, and Ruby wouldn't complain.
Now, however, Ruby wants you to explicitly pass **the_hash instead of just
the_hash where keyword arguments are expected.
The version of public_suffix that this codebase was relying on emitted the
following warnings:
lib/ruby/gems/2.7.0/gems/public_suffix-3.1.1/lib/public_suffix/list.rb:51:
warning: Using the last argument as keyword parameters is
deprecated;
maybe ** should be added to the call
lib/public_suffix/list.rb:69:
warning: The called method `parse' is defined here
v4.0.3 fixes these warnings.
I had to set the version specifier in the gemspec to >= 3.0 in order to manage
to upgrade github/github, …
=> Silence warnings triggered by Ruby 2.7

lib/github-pages-health-check/domain.rb, spec/github_pages_health_check/domain_spec.rb
With the changes in #125, if a domain name is not setup we can hit a scenario where DNS is not responding when we go to check `cname`. This throws an exception instead of returning nil, so it prevents the hash from being created.
=> Guard on cname method having valid dns

lib/github-pages-health-check/domain.rb, spec/github_pages_health_check/domain_spec.rb
In https://github.com/github/pages-health-check/pull/127 we take the approach to abstract SOA record checking from callers to `apex_domain?`.  Existing callers make assumptions around this value not being a subdomain so we may introduce bugs by adding additional logic to the function.
This PR instead exposes the new `dns_zone_soa?` method so that callers can take both pieces of information into account when deciding how to handle cases where subdomains behave like apex domains by having SOA records published.
=> feat(domain): report if an SOA record exists for a domain

github-pages-health-check.gemspec
Resolves an issue when attempting to vendor this project:
```sh
Bundler could not find compatible versions for gem "public_suffix":
In snapshot (Gemfile.lock):
public_suffix (= 4.0.6)
In Gemfile:
public_suffix (~> 4.0)
github-pages-health-check (= 1.7.4) was resolved to 1.7.4, which depends on
public_suffix (~> 2.0)
Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```
/cc https://github.com/github/pages-health-check/pull/116: prior art
=> chore: bump `public_suffix` past ~> 2.0

Gemfile, lib/github-pages-health-check/domain.rb, lib/github-pages-health-check/version.rb, spec/github_pages_health_check/domain_spec.rb
From https://datatracker.ietf.org/doc/html/rfc7719#section-6 (with emphasis on the last sentence).
```
Origin:
(a) "The domain name that appears at the top of a zone (just below
the cut that separates the zone from its parent).  The name of the
zone is the same as the name of the domain at the zone's origin."
(Quoted from [RFC2181], Section 6.)  These days, this sense of
"origin" and "apex" (defined below) are often used
interchangeably.
(b) The domain name within which a given relative domain name
appears in zone files.  Generally seen in the context of
"$ORIGIN", which is a control entry defined in [RFC1035],
Section 5.1, as part of the master file format.  For example, if
the $ORIGIN is set to "example.org.", then a master file line for
"www" is in fact an entry for "www.example.org.". …
```
=> Query DNS to Determine Apex Domains

README.md, script/check
```bash
./script/check pages.github.com
```
vs (which still works)
```bash
bundle exec ./script/check pages.github.com
```
=> Require bundler in script/check to avoid needing to run `bundle exec`.

lib/github-pages-health-check/domain.rb, lib/github-pages-health-check/version.rb, spec/github_pages_health_check/domain_spec.rb
Add check for underscores for custom domain certificates
=> check for underscore for https

.github/workflows/push-cibuild.yml
Actions matrix strategy implies a default of `fail-fast: true`. This saves compute resources but also makes it more hard to determine if a failure if version-specific. 😅 
Let's let them all run since the list is relatively small anyway. 🤷🏻 
**Edit:** Also update the Ruby support matrix based on the official Docker image availability.
=> Allow all of the matrix builds to run despite failures

.github/workflows/push-cibuild.yml, README.md
Noticed this while looking at the README and thought it would be good to get rid of the broken link.
=> Remove the broken Travis CI badge

lib/github-pages-health-check/domain.rb, lib/github-pages-health-check/version.rb, spec/github_pages_health_check/domain_spec.rb
closes: https://github.com/github/pages-engineering/issues/4205
Relaxes the validation process for `CNAME` by checking if the domain it points to points to GitHub Pages. This is done by creating a new method which checks if there is a record of type `A` in the DNS to which the `CNAME` points to. If this is the case then we just check if that points to Pages.
=> Custom domain simplifaction

.github/CODEOWNERS, lib/github-pages-health-check/domain.rb
This PR addresses https://github.com/github/pages-health-check/security/code-scanning/1.
It just does better URL handling by relaying on a regular expression.
=> Fix github.com matching

lib/github-pages-health-check/domain.rb, lib/github-pages-health-check/version.rb, spec/github_pages_health_check/domain_spec.rb
Fix small issue with https://github.com/github/pages-health-check/pull/163.
=> Add a missing nil check around cname_to_domain_to_pages?

lib/github-pages-health-check/resolver.rb
This is a typo. See https://www.rubydoc.info/gems/dnsruby/Dnsruby%2FResolver:initialize
=> Use correct keyword argument when creating Dnsruby::Resolver

github-pages-health-check.gemspec, lib/github-pages-health-check/domain.rb, lib/github-pages-health-check/errors/wildcard_record_error.rb, spec/github_pages_health_check/errors_spec.rb
`Domain#maybe_wildcard?` generates a random sibling domain and queries it, then checks if it returns an answer and if it points to github pages. If so, then it's reasonable to suspect that the record which points the domain to github pages is a wildcard record.
This is worth warning about because a wildcard DNS record will allow anyone to host a pages site at a subdomain of the wildcard record. GitHub allows us to verify ownership of our domains, but it only works for the verified domain and direct subdomains (a.example.com, b.example.com), not subdomains arbitrarily many segments long (a.b.c.d.e.f.example.com).
=> Add Domain.maybe_wildcard? to detect possible wilcard DNS records
